Added Logic Grid Puzzles
dargaCode/LogicAndCodingGames pull request #3
Opened 2022-04-12 23:49 UTC by nfereidooni

I added Logic Grid Puzzles, which is a logic game with words (similar to Sudoku).

2022-04-12 23:54 UTC, dargaCode requested changes

2022-04-12 23:54 UTC, dargaCode commented on README.md
> +      <td></td>
Please also add android and browser

2022-04-12 23:56 UTC, dargaCode commented
is this working? you should get a notiffffffff

2022-04-13 00:00 UTC, nfereidooni commented on README.md
> +      <td></td>
fixed

2022-04-13 00:02 UTC, merged